# Generated by Django 5.2.4 on 2025-08-04 16:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('street_extra', models.CharField(blank=True, max_length=100)),
                ('privacy_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leisure_activities', models.TextField(blank=True)),
                ('church_contact', models.CharField(blank=True, max_length=200)),
                ('needs_transport', models.BooleanField(default=False)),
                ('has_dietary_restrictions', models.BooleanField(default=False)),
                ('dietary_details', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='users.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Junge'), ('female', 'Mädchen')], default='male', max_length=10)),
                ('housing_preference', models.CharField(blank=True, choices=[('family', 'Mit Familie im eigenen Haus'), ('brudershaus', 'Brüderhaus (für Jungen)'), ('sisterhaus', 'Schwesterhaus (für Mädchen)'), ('no_preference', 'Keine Präferenz')], default='family', max_length=20)),
                ('participation_type', models.CharField(choices=[('onsite', 'Vor Ort'), ('online', 'Nur Online')], default='onsite', max_length=20)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('is_full_week', models.BooleanField(default=False, verbose_name='Vollzeit (полное время)')),
                ('is_student', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('food_preference', models.CharField(choices=[('normal', 'Normal'), ('vegetarian', 'Vegetarisch')], default='normal', max_length=20)),
                ('services', models.CharField(blank=True, max_length=200)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Männlich'), ('female', 'Weiblich')], default='male', max_length=10)),
                ('housing_preference', models.CharField(blank=True, choices=[('family', 'Mit Familie im eigenen Haus'), ('brudershaus', 'Brüderhaus (für Männer)'), ('sisterhaus', 'Schwesterhaus (für Frauen)'), ('no_preference', 'Keine Präferenz')], default='family', max_length=20)),
                ('participation_type', models.CharField(choices=[('onsite', 'Vor Ort'), ('online', 'Nur Online')], default='onsite', max_length=20)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('is_full_week', models.BooleanField(default=False, verbose_name='Vollzeit (полное время)')),
                ('is_student', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('comes_with_partner', models.BooleanField(default=False)),
                ('food_preference', models.CharField(choices=[('normal', 'Normal'), ('vegetarian', 'Vegetarisch')], default='normal', max_length=20)),
                ('services', models.CharField(blank=True, max_length=200)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adults', to='users.registration')),
            ],
        ),
    ]
