# Generated by Django 5.2.4 on 2025-07-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('street_extra', models.CharField(blank=True, max_length=100)),
                ('participation_type', models.CharField(choices=[('onsite', 'Vor Ort'), ('online', 'Nur Online')], max_length=20)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('overnight_stays', models.CharField(blank=True, max_length=100)),
                ('is_student', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField()),
                ('comes_with_partner', models.BooleanField(default=False)),
                ('family_members', models.PositiveIntegerField(default=1)),
                ('food_preference', models.CharField(choices=[('normal', 'Normal'), ('vegetarian', 'Vegetarisch'), ('lactose_free', 'Laktosefrei')], max_length=20)),
                ('has_children', models.BooleanField(default=False)),
                ('children_ages', models.CharField(blank=True, max_length=100)),
                ('services', models.CharField(blank=True, max_length=200)),
                ('leisure_activities', models.TextField(blank=True)),
                ('church_contact', models.CharField(blank=True, max_length=200)),
                ('needs_transport', models.BooleanField(default=False)),
                ('has_dietary_restrictions', models.BooleanField(default=False)),
                ('dietary_details', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('privacy_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
