# Generated by Django 5.2.4 on 2025-07-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
