# Generated by Django 5.2.4 on 2025-07-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_participant_children_ages_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
