# Generated by Django 5.2.4 on 2025-07-25 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_participant_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='age',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='church_contact',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='comes_with_partner',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='dietary_details',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='family_members',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='food_preference',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='has_children',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='has_dietary_restrictions',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='leisure_activities',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='needs_transport',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='number_of_children',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='overnight_stays',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='participation_type',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='services',
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_type', models.CharField(choices=[('onsite', 'Vor Ort'), ('online', 'Nur Online')], max_length=20)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('overnight_stays', models.CharField(blank=True, max_length=100)),
                ('is_student', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('comes_with_partner', models.BooleanField(default=False)),
                ('family_members', models.PositiveIntegerField(default=1)),
                ('food_preference', models.CharField(choices=[('normal', 'Normal'), ('vegetarian', 'Vegetarisch'), ('lactose_free', 'Laktosefrei')], max_length=20)),
                ('has_children', models.BooleanField(default=False)),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('services', models.CharField(blank=True, max_length=200)),
                ('leisure_activities', models.TextField(blank=True)),
                ('church_contact', models.CharField(blank=True, max_length=200)),
                ('needs_transport', models.BooleanField(default=False)),
                ('has_dietary_restrictions', models.BooleanField(default=False)),
                ('dietary_details', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='users.participant')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.registration'),
            preserve_default=False,
        ),
    ]
